### ISSUE TITLE
No sound through VAC

### ISSUE THREAD

**Issue by DH1KLM** [dk5qh/SDR_Transceiver_Firmware_Stemlab#1]
Thank you very much for the long-awaited protocol 2 firmware for the Red Pitaya.
I just tried it in terms of reception, but unfortunately I get no sound via VAC1 with the same thetis configuration with Pavel's original firmware.
When Pavel's firmware is loaded, the sound is heard again immediately.

Did I miss something?

Thetis version is 2.8.11 in 32bit and 64 bit.

btw.
Why is there a Angelia and Orion folder. Do the two firmware behave differently?

**Comment by dk5qh** [comment]
The audio processing takes place in Thetis, the processing for protocol 1 and protocol 2 is totally different and takes place in different parts of the Thetis. This makes different behavior possible. There is no experience about alternating use of protocol 1 and protocol 2 with the same Thetis installation.  However, in one case I had a problem with VAC when installing Thetis (64bit still for protocol 2) for the first time. With the many installations of the beta-testers the described problem did never occur although there are several entries about Thetis and VAC in the forums. Please have a look to that as well.
 
In my case I finally removed VAC from my computer and reinstalled it. This solved the problem. I used Virtual-Audio-Cable (https://virtual-audio-cable.de). Do not forget to allow program access to the microphone on Windows 10.

The difference in the behavior of the firmware between Angelia- and Orion-emulation is negligible at the moment. Just make sure that the setting in the PC program fits to it.

**Comment by DH1KLM** [comment]
Thanks for your quick answer.
By VAC, I actually meant Theti's own VAC1 and VAC2 function.
I am not using an external VAC program.

However, I will try it with a new database and see if this will solve my issue.
On the other side, a Hermes with prot. 2 is running with out problems with the same Thetis installation.

**Comment by DH1KLM** [comment]
A new database does not solve the problem.
In the meantime, I've tried 3 different PCs with no success. One of them is a completely new Win10 installation.
2 computers with Win10 2H20 and 1 are running Win10 1909.
Tried various hardware settings in Thetis.
When Angelia is running, Thetis is configured as Anan 100D. Should be okay so far.
When I run Orion MKII, I put Thetis on Anan 7000.
No audio in either case.

**Comment by dk5qh** [comment]
Your described issue is unknown to the users who use the firmware for a longer period and did never occur.  With all users the start-up ran completely problem-free. Regarding VAC there are users without and users who work with the proposed software. 
Nevertheless you should be able to work successfully with this firmware. So a few questions, so that I can think along:
- which board do you use?
- which image and which Thetis version?
- which interfaces are wired on the board?
- which CODEC is used?
- do **all** other functions of the software work, RX in waterfall, TX,... ?
- is the audio signal available at the CODEC headphone output?
- is the VAC1 button on Thetis active or does it stay dark?

**Comment by DB8BH** [comment]
I use Thetis 2.8.11 on Win10_64 2H20 with the new Firmware on Stemlab 16Bit without any problem.

Regarding the "Sound problem":  Usually I use a virtual audio cable (VAC 4.62) to connect Thetis with WSJT-X. In the Thetis Audio Setup I have to choose <Windows Direct Sound, Line1, Line1>. If I don't use the virtual audio cable, I have to change the Thetis settings to <MME, Sound Mapper, Sound Mapper>.

Anyway, this has nothing to do with the Stemlab Firmware, obviously .

**Comment by DH1KLM** [comment]
•	14 Bit Red Pitaya
•	Latest Image from Pavel 20200628
•	BCD Controller for LPF switching
•	No codec board. All Audio is via Thetis VAC 1
•	All other functions are working as far as I can see. No modulation in TX. 
•	No codec board. All Audio is via Thetis VAC 1
•	VAC 1 button is active
•	Win10 2H20
•	Thetis 2.8.11
•	In Thetis VAC 1 Audio Setup MME is choosen. Also found Windows Direct Sound not working.
•	IN/OUT is set to Microsoft Soundmapper

Further tests are done with a fresh installed Win10 and Thetis 2.8.11
I found that under Thetis/Setup/Tests no signal is generated under Two Tone Test.
The TRX goes to TX without modulation.

As I said before, the TRX with Pavel's latest Image works with PowerSDR and Thetis 2.8.11 without any problems.

I also have an older image from Pavel which I am going to test now and report back.

**Comment by dk5qh** [comment]
Thank you very much for the detailed description, which allows a clear determination of the cause.
- with VAC there is no problem, the activation of VAC1 by Thetis shows this
- the negative is that you don't use a CODEC, so all AF signals are missing. According to the emulated boards, which basically have CODECs, the firmware is also realized that way. As you might know in the Stemlab world for latency reasons usually separate CODEC boards (with WM8731) are used. I'm sorry that I didn't realize earlier that you couldn't use a CODEC, that would have saved you a lot of trouble in the search
- One more hint:  - as mentioned in the _readme_ and shown in the _DL0SDR project_ - not all interfaces built into protocol 1 have been implemented in this new designed firmware. Reason is that there are many "dead" and several interfaces with the same content. Increased requirements by protocol 2 were another reason. It was made sure that no information is missing and the most frequently used ones are available. However, these are increased in their performance.

We will take this issue as a reason to leave a more detailed note here.

Again, sorry for your test effort. I think you will be able to extend your Stemlab easily with the cheap CODEC board.

**Comment by DH1KLM** [comment]
OK, of course that explains everything.
Anyway, I'm thinking of revising my Red Pitaya TRX, then a codec board will also be built in.

I should have written in my first post that I don't use a codec board.
Since I hadn't used a codec board before, I didn't think that this could be the reason for my problem.

Thanks for your help and for the project in particular.
