### ISSUE TITLE
issues with licenses

### ISSUE THREAD

**Issue by pavel-demin** [dk5qh/SDR_Transceiver_Firmware_Stemlab#2]
I'd like to attract your attention to two possible issues with licenses.

1. The GPLv3 license requires that you provide the source code. However, I can't find the source code in this repository. So, please provide the source code.

2. In the README.md file you write that the software is based on [my code](https://github.com/pavel-demin/red-pitaya-notes). My code is provided under the terms of the [MIT license](https://github.com/pavel-demin/red-pitaya-notes/blob/master/LICENSE). The  [MIT license](https://github.com/pavel-demin/red-pitaya-notes/blob/master/LICENSE) requires that the copyright notice and the text of the license be included in all copies or substantial parts of the software. However, I can't find them in this repository. So, please copy the [MIT license](https://github.com/pavel-demin/red-pitaya-notes/blob/master/LICENSE) file from my repository to this repository.

**Comment by dk5qh** [comment]
Thank you very much for your hint.
I think we agree that licensing discussions do not add value to the pro bono provision of code to the HAM radio community. This is the only purpose of this release.
To close the issue the license file has been replaced by a legally verified formulation based on MIT.

**Comment by pavel-demin** [comment]
Thanks for updating the license file. It looks better now.

However, the following part looks strange:
```
In case that this program contains snippets of code originating from 
https://github.com/pavel-demin/red-pitaya-notes and these would constitute a 
copyright to Pavel Demin, "The MIT LIcence (MIT)" as listed below shall apply in full.
```

As far as I know, this project uses the [FPGA configuration from my repository](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/sdr_transceiver_hpsdr_122_88). This corresponds to about 1500 lines of code. It's about 30-40% of the total size of the code in this project.

The word "snippet" means "small piece or brief extract". I wouldn't call 30-40% of the code a "snippet".

Please change the wording of the part mentioning my code in the license file to something that better reflects reality.

**Comment by pavel-demin** [comment]
I've just realized that I forgot to count the IP cores in my repository used in this project. With the IP cores, the FPGA configuration is about 3.5k lines of code or about 50-60% of the total code size in this project.

Since this issue is already closed, I've just opened a [new one](https://github.com/dk5qh/SDR_Transceiver_Firmware_Stemlab/issues/4).
